echo 10 > /sys/class/gpio/export
echo 9 > /sys/class/gpio/export
echo 11 > /sys/class/gpio/export
echo 8 > /sys/class/gpio/export
echo 14 > /sys/class/gpio/export
echo 25 > /sys/class/gpio/export
echo 24 > /sys/class/gpio/export
echo 22 > /sys/class/gpio/export
echo 2 > /sys/class/gpio/export
echo 3 > /sys/class/gpio/export
echo 4 > /sys/class/gpio/export
echo 27 > /sys/class/gpio/export
echo 21 > /sys/class/gpio/export
echo 20 > /sys/class/gpio/export
echo 12 > /sys/class/gpio/export
